version: "3.7"

services:
  nginx:
    build: ./nginx-proxy
    volumes:
      - static_volume:/app/staticfiles
      - ./media_volume:/app/media
    ports:
      - 81:80
    depends_on:
      - web
    restart: on-failure:5
  web:
    build:
      context: ./web-project
      dockerfile: Dockerfile.prod
    command: gunicorn docker_proj.wsgi:application --workers 2 --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - ./media_volume:/app/media # ./ will mount the dir on the host, if you don't want to store them on host remove ./
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    build:
      context: ./postgres-db
    volumes:
      - ./postgres-db:/var/lib/postgresql
    env_file:
      - .env.prod

volumes:
  postgres_data:
  static_volume:
  media_volume:
