version: "3.7"

services:
  web:
    build:
      context: ./web-project
      dockerfile: Dockerfile
    volumes:
      - ./web-project:/app
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    build:
      context: ./postgres-db
      dockerfile: Dockerfile
    volumes:
      - ./postgres-db:/var/lib/postgresql
    env_file:
      - .env.dev

  worker:
    build:
      context: ./web-project
      dockerfile: Dockerfile.worker
    command: celery worker --app=django_project -B --loglevel=info --logfile=celery.log
    volumes:
      - ./web-project:/app
    env_file:
      - .env.dev
    depends_on:
      - web
      - redis

  redis:
    build: ./redis
